name: Release Prerelease

on:
  push:
    branches:
      - prerelease

permissions:
  contents: write
  pull-requests: write

jobs:
  release-please:
    runs-on: ubuntu-latest
    steps:
      - uses: googleapis/release-please-action@v4
        id: release
        with:
          token: ${{ secrets.AUTOMATION_TOKEN }}
          target-branch: prerelease