name: Tag Deploy for prerelease branch

on:
  push:
    tags:
      - 'v*'

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
      - name: Echo Test Deploy prerelease
        run: echo "TEST DEPLOY prerelease BRANCH" 